language: python
python:
- '3.6'
sudo:
- required
install:
- pip install html5validator
script: html5validator
notifications:
  slack: comp680boctor:8OXuyAwv1IOXRXcW48IE1Fex

addons:
  artifacts:
    s3_region: "us-west-2" # defaults to "us-east-1"
